language: python
python:
- '3.6'
env:
- DJANGO=2.0
install:
- cd gmooc/
- pip install -r requirements.txt
script:
    # - python manage.py test users
before_install:
- openssl aes-256-cbc -K $encrypted_2bc13221a680_key -iv $encrypted_2bc13221a680_iv
  -in id_rsa_deploy.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- export MYSQL_USER=$MYSQL_USER
- export MYSQL_PASSWORD=$MYSQL_PASSWORD
addons:
    ssh_known_hosts: 13.125.15.159
after_success:
- ssh ubuntu@13.125.15.159 'cd ~/projects/GMOOC && git pull && pkill uwsgi'
